# email_sender.py
"""
Email automation module for sending reports via Gmail SMTP.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime
import os
import logging
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Set up logger
logger = logging.getLogger(__name__)


def send_email_report(report_path, recipient_email=None, stats=None):
    """
    Send Excel report via email with attachment.
    
    Parameters:
    - report_path: Path to the Excel file to attach
    - recipient_email: Who to send it to (default: from .env)
    - stats: Dictionary with summary stats (files, rows, locations, etc.)
    
    Returns:
    - True if email sent successfully, False otherwise
    """
    
    # Get credentials from .env
    sender_email = os.getenv('email')
    sender_password = os.getenv('password')
    
    # If recipient not provided, use default from .env
    if recipient_email is None:
        recipient_email = os.getenv('email')
    
    # Validate credentials
    if not sender_email or not sender_password:
        logger.error("❌ Missing email credentials in .env file")
        logger.error("   Please set 'email' and 'password' in .env")
        return False
    
    if not recipient_email:
        logger.error("❌ No recipient email provided")
        return False
    
    try:
        # Create email
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        
        # Subject with date
        msg['Subject'] = f"🏥 Healthcare Report - {datetime.now().strftime('%B %Y')}"
        
        # Prepare stats for email body
        if stats is None:
            stats = {}
        
        total_patients = stats.get('total_patients', 0)
        total_revenue = stats.get('total_revenue', 0)
        total_visits = stats.get('total_visits', 0)
        locations = stats.get('locations', 0)
        
        # HTML email body
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2 style="color: #1a5276;">🏥 Healthcare Monthly Report</h2>
            <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
            
            <h3>📊 Summary Statistics</h3>
            <table border="1" cellpadding="8" style="border-collapse: collapse; width: 50%;">
                <tr style="background-color: #366092; color: white;">
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
                <tr><td>Total Patients</td><td style="text-align: right;">{total_patients}</td></tr>
                <tr><td>Total Revenue</td><td style="text-align: right;">${total_revenue:,.2f}</td></tr>
                <tr><td>Total Visits</td><td style="text-align: right;">{total_visits}</td></tr>
                <tr><td>Clinics</td><td style="text-align: right;">{locations}</td></tr>
            </table>
            
            <p style="margin-top: 20px; color: #666; font-size: 12px;">
                This report was auto-generated by the Healthcare Automation System.
            </p>
            
            <p style="color: #666; font-size: 12px;">
                For questions, please reply to this email.
            </p>
        </body>
        </html>
        """
        msg.attach(MIMEText(body, 'html'))
        
        # Attach the report file
        if Path(report_path).exists():
            with open(report_path, 'rb') as f:
                part = MIMEBase('application', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet')
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header(
                    'Content-Disposition',
                    f'attachment; filename={Path(report_path).name}'
                )
                msg.attach(part)
                logger.info(f"📎 Attached: {Path(report_path).name}")
        else:
            logger.warning(f" Report not found: {report_path}")
            # Continue without attachment
        
        # Send email via Gmail SMTP
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
        
        logger.info(f"📧 Email sent successfully to {recipient_email}")
        return True
        
    except smtplib.SMTPAuthenticationError:
        logger.error("❌ Gmail authentication failed!")
        logger.error("   Check your email and app password in .env")
        return False
    except smtplib.SMTPException as e:
        logger.error(f" SMTP error: {e}")
        return False
    except Exception as e:
        logger.error(f" Failed to send email: {e}")
        logger.exception("Email error details:")
        return False


def send_test_email():
    """Send a test email to verify credentials work."""
    stats = {
        'total_patients': 0,
        'total_revenue': 0,
        'total_visits': 0,
        'locations': 0
    }
    return send_email_report(None, None, stats)


# ==================== HOW TO USE ====================

if __name__ == "__main__":
    # Test the module
    print(" Sending test email...")
    send_test_email()